package com.qa.testdrivendevelopment;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertFalse;
import static org.junit.Assert.assertNull;
import static org.junit.Assert.assertTrue;

import org.junit.Test;

/**
 * Test file for Questions Class.
 * 
 * The first questions have been completed for you, 
 * there are 10 other questions.
 * 
 * Run this file to see how well you are doing.
 * 
 * DO NOT EDIT THIS FILE!
 * 
 * An extra test (which is secret) will run on these tests after submission
 * So it is not recommended that you "hard code" solutions.
 * i.e. if (input.equals("John")) return "Hi John"
 * 
 */
public class QuestionTest {

	private Questions questions = new Questions();	
	
	
	@Test
	public void letsADDTest() {
		assertEquals(25, questions.letsADD(10,15));
		assertEquals(100, questions.letsADD(50,50));
		assertEquals(1100, questions.letsADD(100,1000));
	}
		
}